
- include_vars: "Archlinux.yml"

- name: Include ubuntu tasks
  include_tasks: "{{ item }}"
  loop:
    - pacman.yml
    - aur.yml
    - lsd.yml
  tags: ["init", "arch"]
  when: ansible_distribution == "Archlinux"