---
- include_vars: "Archlinux.yml"
  tags: always
  when: ansible_distribution == "Archlinux"

- name: Include base arch tasks
  include_tasks: "{{ item }}"
  loop:
    - yay.yml
    - pacman.yml
  tags: always
  when: ansible_distribution == "Archlinux"

# - name: Include DE arch 
#   include_tasks: "{{ item }}"
#   loop:
#     - sddm.yml
#     - hyprland/hyprland.yml
#     - hyprland/wofi.yml
#   tags: ["de", "hyprland"]
#   when: ansible_distribution == "Archlinux"

