
- include_vars: "Archlinux.yml"
  tags: always
  when: ansible_distribution == "Archlinux"

- name: Include ubuntu tasks
  include_tasks: "{{ item }}"
  loop:
    - yay.yml
    - pacman.yml
    - aur.yml
  tags: always
  when: ansible_distribution == "Archlinux"