---
- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    clone: yes
    update: no
  tags: &tags_for_yay_tasks ["init", "yay"]

- name: Build and install yay
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/yay
  register: makepkg_result
  failed_when: makepkg_result.rc != 0
  tags: *tags_for_yay_tasks

- name: Remove yay build directory
  file:
    path: /tmp/yay
    state: absent
  tags: *tags_for_yay_tasks

- name: Install pkgs
  shell: "yay -S oh-my-posh downgrade"
  become: yes
  become_user: root
  tags: *tags_for_yay_tasks

