---
- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    clone: yes
    update: no
  tags: &tags_for_yay_tasks ["init", "yay"]

- name: Build and install yay
  command: makepkg -si
  args:
    chdir: /tmp/yay
  register: makepkg_result
  failed_when: "'installed' not in makepkg_result.stdout"
  tags: *tags_for_yay_tasks
  
- name: Remove yay build directory
  file:
    path: /tmp/yay
    state: absent
  tags: *tags_for_yay_tasks