---
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Apply common changes
  ansible.builtin.include_tasks: common/main.yml
  tags: always

- name: Apply common changes
  ansible.builtin.include_tasks: arch/main.yml
  when: ansible_distribution == "Archlinux"
  tags: always

- name: Apply common changes
  ansible.builtin.include_tasks: ubuntu/main.yml
  when: ansible_distribution == "Ubuntu"
  tags: always


