---
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- include_task: common/main.yml
    
- include_task: arch/main.yml
  when: ansible_distribution == "Archlinux"

- include_task: ubuntu/main.yml
  when: ansible_distribution == "Ubuntu"

