- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- include: common/main.yml
    
- include: arch/main.yml
  tags: arch
  when: ansible_distribution == "Archlinux"

- include: ubuntu/main.yml
  tags: ubuntu
  when: ansible_distribution == "Ubuntu"
