---
- name: Install dependencies for mako
  package:
    name: "{{ mako.deps }}"
    state: present
  become: true
  tags: &tags_for_mako_tasks ["init", "mako", "sway"]

- name: "Make sure the {{ mako.clone_path }} exists"
  file:
    path: "{{ mako.clone_path }}"
    state: directory
    recurse: yes
  tags: *tags_for_mako_tasks

- name: Clone the mako project
  git:
    repo: https://github.com/emersion/mako
    dest: "{{ mako.clone_path }}"
    force: true
    update: "{{ upgrade | default(false) }}"
  tags: *tags_for_mako_tasks

- name: Run meson build
  command:
    cmd: "meson build"
    chdir: "{{ mako.clone_path }}"
  changed_when: false
  tags: *tags_for_mako_tasks

- name: Install using ninja
  command:
    cmd: "sudo ninja -C build install"
    chdir: "{{ mako.clone_path }}"
    warn: false
  changed_when: false
  become: yes
  become_user: root
  tags: *tags_for_mako_tasks

- name: Remove mako folder
  file:
    state: absent
    path: "{{  mako.clone_path }}"
  become: yes
  become_user: root
  tags: *tags_for_mako_tasks