---
- name: Install dependencies for wlsunset
  package:
    name: "{{ wlsunset.deps }}"
    state: present
  become: true
  tags: &tags_for_sunset_tasks ["init", "sunset", "sway"]

- name: "Make sure the {{ wlsunset.clone_path }} exists"
  file:
    path: "{{ wlsunset.clone_path }}"
    state: directory
    recurse: yes
  tags: *tags_for_sunset_tasks

- name: Clone the wlsunset project
  git:
    repo: https://git.sr.ht/~kennylevinsen/wlsunset
    dest: "{{ wlsunset.clone_path }}"
    force: true
    update: "{{ upgrade | default(false) }}"
  tags: *tags_for_sunset_tasks

- name: Run meson build
  command:
    cmd: "meson build"
    chdir: "{{ wlsunset.clone_path }}"
  changed_when: false
  tags: *tags_for_sunset_tasks

- name: Install using ninja
  command:
    cmd: "sudo ninja -C build install"
    chdir: "{{ wlsunset.clone_path }}"
    warn: false
  become: yes
  become_user: root
  changed_when: false
  tags: *tags_for_sunset_tasks

- name: Remove wlsunset folder
  file:
    state: absent
    path: "{{  wlsunset.clone_path }}"
  become: yes
  become_user: root
  tags: *tags_for_sunset_tasks