---
- name: Install basic packages
  apt:
    name: 
      - build-essential
      - fd-find
    state: present
  become: yes
  become_user: root
  tags: &tags_for_package_tasks_apt ["init", "packages"]

- name: ripgrep (not apt) 
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  become: yes
  become_user: root
  tags: *tags_for_package_tasks_apt
  

- name: duf (not apt) 
  apt:
    deb: https://github.com/muesli/duf/releases/download/v0.6.0/duf_0.6.0_linux_amd64.deb
  become: yes
  become_user: root
  tags: *tags_for_package_tasks_apt
