- name: Install basic packages
  apt:
    name: 
      - build-essential
      - wl-clipboard
      - fd-find
    state: present
  become: yes
  tags: ["init", "packages"]
  become_user: root

- name: ripgrep (not apt) 
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  become: yes
  become_user: root
  tags: lsd

