- name: Reqired libraries for brave
  apt:
    name: ["curl", "apt-transport-https"]
  become: yes
  become_user: root
  tags: &tags_for_brave_tasks ["init", "brave"]

- name: Brave Browser archive-keyring.gpg download
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: yes
  become_user: root
  tags: *tags_for_brave_tasks

- name: Brave Browser PPA setting
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-relase.list
  become: yes
  become_user: root
  tags: *tags_for_brave_tasks

- name: Brave Browser apt installation
  apt:
    update_cache: yes
    name: brave-browser
  tags: *tags_for_brave_tasks
  become: yes
  become_user: root
