---
- include_vars: "Ubuntu.yml"
  tags: always
  when: ansible_distribution == "Ubuntu"

- name: Include ubuntu tasks
  include_tasks: "{{ item }}"
  loop:
    - apt.yml
    - lsd.yml
    - snap.yml
  tags: always
  when: ansible_distribution == "Ubuntu"

