
- include_vars: "Ubuntu.yml"

- include: apt.yml
  when: ansible_distribution == "Ubuntu"

- include: brave.yml
  when: ansible_distribution == "Ubuntu"

- include: lsd.yml
  when: ansible_distribution == "Ubuntu"

- include: snap.yml
  when: ansible_distribution == "Ubuntu"
