- include_vars: "Ubuntu.yml"

- name: Include ubuntu tasks
  include_tasks: "{{ item }}"
  loop:
    - apt.yml
    - brave.yml
    - lsd.yml
  tags: ["init", "ubuntu"]
  when: ansible_distribution == "Ubuntu"

