- name: Remove snap
  apt:
    name:
      - snapd
    state: absent
    purge: yes
  become: yes
  become_user: root
  tags: &tags_for_snap_tasks ["r_snap"]

- name: Remove snap folder
  file:
    state: absent
    path: "/home/{{ username }}/snap"
  tags: *tags_for_snap_tasks

- name: Block snap
  copy:
    src: files/nosnap.pref
    dest: "/etc/apt/preferences.d/nosnap.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  become_user: root
  tags: *tags_for_snap_tasks

- name: Update cache
  apt:
    update_cache: true
    state: present
  become: yes
  become_user: root
  tags: *tags_for_snap_tasks

- name: Install faltpak
  apt:
    name:
      - flatpak
    state: present
  become: yes
  become_user: root
  tags: &tags_for_flatpak_tasks ["init", "flatpak"]
