---
- name: Install dependencies sddm (dm)
  community.general.pacman:
    name:
      - sddm
  become: yes
  become_user: root
  tags: &tags_for_sddm_tasks [ "de", "sddm" ]

- name: Install sddm theme dependencies
  community.general.pacman:
    name:
      - qt5-graphicaleffects
      - qt5-quickcontrols2 
      - qt5-svg
  become: yes
  become_user: root
  tags: *tags_for_sddm_tasks

- name: Create the sddm theme folder
  file:
    path: "/usr/share/sddm/themes"
    state: directory
    recurse: yes
  become: yes
  become_user: root
  tags: *tags_for_sddm_tasks

- name: Copy theme
  copy:
    src: files/{{ sddm.theme }}
    dest: "/usr/share/sddm/themes"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  become: yes
  become_user: root
  tags: *tags_for_sddm_tasks

- name: "Set theme {{ sddm.theme }}"
  command:
    cmd: "sed -i 's/Current=.*/Current={{ sddm.theme }}/' /usr/lib/sddm/sddm.conf.d/default.conf"
  become: yes
  become_user: root
  tags: *tags_for_sddm_tasks
