## AUR vars
## ===========================
use_aur: True

aur:
    dir: aur
    packages:
        - yay
        - downgrade
        - zplug
        - miller
        - myrepos
        - ctmg
        - spiped
## ===========================

