- name: Download cloudflared binary
  get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: "/home/{{ username }}/cloudflared"
    mode: '0755'
  tags: ["cloudflared"]

