- name: Install basic utils apps, shells, apps
  package:
    name:
      - kitty
      - vlc
      - git
      - tmux
      - vim
      - tree
      - ranger
      - cmake
      - pavucontrol
      - arandr
      - python3
      - ncdu # manage space
      - sxhkd
      - wl-clipboard
      - flameshot
      - bat # cat figo
      - htop
      - httpie # richeiste http
      - net-tools
      - jq
    state: present
  become: yes
  become_user: root
  tags: &tags_for_package_tasks ["init", "packages"]

- name: Install archival utils
  package:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - zip
      - bzip2
      - gzip
      - tar
    state: present
  become: yes
  become_user: root
  tags: *tags_for_package_tasks

- name: Install download utils
  package:
    name:
      - aria2
      - curl
      - wget
    state: present
  become: yes
  become_user: root
  tags: *tags_for_package_tasks

- name: Install Zoxoide
  shell: "curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash"
  become: yes
  become_user: root
  tags: *tags_for_package_tasks

- name: Install firefox
  package:
    name:
      - firefox
    state: present
  become: yes
  become_user: root
  tags: ["init", "firefox"]
