- name: Install basic utils apps, shells, apps
  package:
   name:
     # - thefuck
    - xorg
    - kitty
    - vlc
    - git
    - tmux
    - vim
    - tree
    - ranger
    - cmake 
    - pavucontrol
    - arandr
    - python3
   state: present

- name: Install archival utils
  package:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  package:
    name:
      - aria2
      - curl
      - wget
    state: present

