- name: Clone user dotfiles
  ansible.builtin.git: 
    repo: "{{ dotfiles.url }}"
    dest: "/home/{{ username }}/{{ dotfiles.destination }}" 
    bare: yes
    update: no
    recursive: yes
    version: master
  become: yes
  become_user: "{{ username }}"

# - name: Setting config as alias of bare repo
#   command: "alias config='/usr/bin/git --git-dir=/home/{{ username }}/.cfg/ --work-tree=$HOME'"
#   become: yes
#   become_user: "{{ username }}" 
- name: Create backup folder
  command: "mkdir -p /home/{{ username }}/.config-backup"
  become: yes
  become_user: "{{ username }}" 

- name: Backup old config
  vars:
    regex: "\\\\s+\\\\."
  shell: "{{ dotfiles.alias }} checkout 2>&1 | grep -E {{ regex }} | grep -v \"^M\" | awk {'print $1'} | xargs -I{} mv /home/{{ username }}/{} /home/{{ username }}/.config-backup/{}"
  become: yes
  become_user: "{{ username }}" 

- name: Git remove showUntrackedFiles
  shell: "{{ dotfiles.alias }} config --local status.showUntrackedFiles no"
  become: yes
  become_user: "{{ username }}" 

- name: Checkout and ready to go 
  shell: "{{ dotfiles.alias }} checkout -f"
  become: yes
  become_user: "{{ username }}" 

- name: Remove extra dotfiles files (README.md, ...)
  ansible.builtin.file:
    path: "rm /home/{{ username }}/README.md"
    state: absent
  become: yes
  become_user: "{{ username }}" 

