---
- name: Look for already installed kitty
  shell: "which kitty"
  register: kitty_installed
  ignore_errors: True
  changed_when: False

- name: 'Try to install "kitty-terminfo"'
  package:
    name: kitty-terminfo
    state: latest
  ignore_errors: yes
  register: kitty_terminfo_installed
  when: kitty_installed is failed

- name: "If no kitty(-terminfo) available, install manually"
  include_tasks: manual_kitty.yml
  when: kitty_terminfo_installed is failed and kitty_terminfo_installed is defined and kitty_terminfo_installed is failed
