- name: Include default tasks
  include_tasks: "{{ item }}"
  loop:
    - core-apps.yml
    - ssh.yml
    - git.yml
    - dotfiles.yml
    - node.yml
    - nvim.yml
    - zsh.yml
    - kitty.yml
    # - i3.yml
  tags: always
