- name: Install basic packages (ubuntu)
  apt:
    name: 
      - build-essential
    state: present
  become: yes
  become_user: root
  when: ansible_distribution == "Ubuntu"


- name: Install basic packages (arch)
  community.general.pacman:
    name: 
      - base-devel
    state: present
  become: yes
  become_user: root
  when: ansible_distribution == "Archlinux"

- name: Include default tasks
  include_tasks: "{{ item }}" 
  loop: 
    - core-apps.yml
    - ssh.yml
    - git.yml
    - dotfiles.yml
    - node.yml
    - vim.yml
    - zsh.yml
  tags: always

