---
- name: Remove fnm
  file:
    path: "/home/{{ username }}/.local/share/fnm"
    state: absent
  tags: &tags_for_node_tasks 
    - init
    - nodejs

- name: Install fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "/home/{{ username }}/.local/share/fnm" --skip-shell
  tags: *tags_for_node_tasks
  args:
    warn: false

- name: Install correct version of Node
  shell: "/home/{{ username }}/.local/share/fnm/fnm install {{ nodejs.version }}"
  tags: *tags_for_node_tasks
  args:
    executable: /bin/bash

- name: Select default version of Node
  shell: "/home/{{ username }}/.local/share/fnm/fnm default {{ nodejs.version }}"
  tags: *tags_for_node_tasks
  args:
    executable: /bin/bash