---
- name: Install nodejs and npm
  package: 
    name: 
      - nodejs
      - npm
    state: present
  become: yes
  become_user: root
  tags: &tags_for_node_tasks ["install", "node", "nvm", "npm"]

- name: Install nvm 
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    warn: false
  register: nvm_installed
  tags: *tags_for_node_tasks

- name : source bash profiles
  shell : source /home/{{ username }}/.bashrc
  when: nvm_installed
  register: sourced

- name: Install correct version of Node
  shell: >
    nvm install 14 && nvm alias default node
  when: sourced
  tags: *tags_for_node_tasks
    
- name: Install Typescript
  npm:
    name: typescript
    global: yes
  tags: *tags_for_node_tasks

- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
  tags: *tags_for_node_tasks

- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
  tags: *tags_for_node_tasks

- name: Install eslint server
  npm:
    name: vscode-langsrvers-extracted
    global: yes
  tags: *tags_for_node_tasks
