- name: Create .ssh folder
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
  tags: &tags_for_ssh_tasks ["install", "ssh"]

- name: Copy ssh key (private)
  copy:
    src: files/id_rsa
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
  tags: *tags_for_ssh_tasks

- name: Copy ssh keys (public) 
  copy:
    src: files/id_rsa.pub
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  tags: *tags_for_ssh_tasks