- name: Create .ssh folder
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory

- name: Copy ssh key (private)
  copy:
    src: files/id_rsa
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Copy ssh keys (public) 
  copy:
    src: files/id_rsa.pub
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
