---
username: jako

include_dotfiles: True

nodejs:
  version: 20.8.0

nvim:
  build: True
  build_type: "RelWithDebInfo"
  clone_path: "/home/{{ username }}/.neovim-build"

dotfiles:
  url: git@github.com:hiimjako/dotfiles.git
  destination: .cfg
  alias: /usr/bin/git --git-dir=/home/{{username}}/.cfg/ --work-tree=/home/{{username}}

git:
  mail: "moretti919@gmail.com"
  username: "jako"

## Desktop
sway_packages:
  - sway
  - waybar
  - wl-clipboard
  - grim
  - slurp
  - kanshi
  - playerctl
  - pavucontrol
  - swaylock
  - swayidle

wofi:
  clone_path: "/tmp/wofi"
  deps:
    - mercurial
    - libwayland-dev
    - libgtk-3-dev
    - pkg-config
    - meson
    - ninja-build
      
mako:
  clone_path: "/tmp/mako"
  deps:
    - git
    - libsystemd-dev
    - libgdk-pixbuf2.0-dev
    - meson
    - libcairo2-dev
    - libpango1.0-dev
    - scdoc
    - jq
    - ninja-build

wlsunset:
  clone_path: "/tmp/sunset"
  deps:
    - git
    - meson
    - ninja-build
    - scdoc
