- name: create .ssh folder
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory

- name: copy ssh keys
  copy:
    src: files/id_rsa
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy ssh keys pub
  copy:
    src: files/id_rsa.pub
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
