--- 
branch: master
username: jako

setup_zsh: True
pull_dotfiles: True

dotfiles:
    url: git@github.com:hiimjako/dotfiles.git
    destination: .cfg

## Desktop
install_i3: True

browser: brave

## Spacevim? You know you need it
install_spacevim: True

## AUR vars
## ===========================
use_aur: True

aur:
    dir: aur
    packages:
        - yay
        - downgrade
        - zplug
        - miller
        - myrepos
        - ctmg
        - spiped
## ===========================
