- name: Clone user dotfiles
  ansible.builtin.git: 
    - repo: "{{ dotfiles.url }}"
    - dest: "/home/{{ username }}/{{ dotfiles.destination }}" 
    - bare: yes
    - update: no
    - recursive: yes
    - version: master
  become: yes
  become_user: "{{ username }}"

- name: Install user dotfiles
  command: 
    - alias config='/usr/bin/git --git-dir=/home/{{ username }}/.cfg/ --work-tree=$HOME'
    - mkdir -p .config-backup && config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
    - config config --local status.showUntrackedFiles no
  become: yes
  become_user: "{{ username }}" 
