
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- include: pacman.yml
- include: core-apps.yml
- include: aur-apps.yml
  when: ansible_distribution == "Archlinux"

# Install and configure spacevim
- include: vim.yml

- include: node.yml
- include: git.yml


