- name: install zsh
  community.general.pacman:
    name: 
     - zsh
     - zsh-completions
     - zsh-syntax-highlighting
    state: present
    become: yes
    become_user: '{{ username }}'

- name: install ranger for zsh
  community.general.pacman:
    name: 
     - ranger
    state: present
    become: yes
    become_user: '{{ username }}'

- name: clone oh-my-zsh for users
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: yes
  become_user: '{{ username }}'
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '~{{ username }}'
    creates: '~{{ username }}/.oh-my-zsh'

- name: change "{{ username }}"'s shell to zsh
  become: yes
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: Remove Oh-My-Zsh if installed
  shell: uninstall_oh_my_zsh
  warn: no
  become: yes
  become_user: '{{ username }}'

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
  become: yes
  become_user: '{{ username }}'

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "${ZSH_CUSTOM:-~/.oh-my-zsh/}/plugins/zsh-syntax-highlighting"
  become: yes
  become_user: '{{ username }}'

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "${ZSH_CUSTOM:-~/.oh-my-zsh/}/plugins/zsh-autosuggestions"
  become: yes
  become_user: '{{ username }}'

# - name: copy zsh dotfile
#   copy: 
#    src: /home/{{username}}/.zshrc 
#    dest: /home/{{ username }}/.zshrc
#    force: False
#    owner: "{{ username }}"
#    group: "{{ username }}"
#    mode: u+rw,g+r,o--
#   when: include_dotfiles == True

# - name: copy zsh p10k dotfile
#   copy: 
#    src: /home/{{ username }}/.p10k.zsh
#    dest: /home/{{ username }}/.p10k.zsh
#    force: False
#    owner: "{{ username }}"
#    group: "{{ username }}"
#    mode: u+rw,g+r,o--
#   when: include_dotfiles == True

- name: clone powerlevel10k theme
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  become: yes
  become_user: '{{ username }}'

